import { session } from 'electron';
import { createHash } from 'node:crypto';
import { mkdirSync, mkdtempSync, rmSync, statfsSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';

/** Electron extensions require a persistent context; its backing can be RAM. */
export class RamSessions {
  private directory?: string;
  private contexts = new Map<string, Electron.Session>();
  static supported(): boolean {
    try {
      const base = process.platform === 'linux' ? '/dev/shm' : tmpdir();
      const filesystem = statfsSync(base);
      return filesystem.bavail * filesystem.bsize >= 32 * 1024 * 1024;
    } catch { return false; }
  }
  open(id: string): Electron.Session {
    const existing = this.contexts.get(id);
    if (existing) return existing;
    if (!RamSessions.supported()) throw new Error('Native extensions require an available Linux tmpfs with at least 32 MB free.');
    const base = process.platform === 'linux' ? '/dev/shm' : tmpdir();
    this.directory ??= mkdtempSync(join(base, 'astra-extensions-'));
    const path = join(this.directory, createHash('sha256').update(id).digest('hex'));
    mkdirSync(path, { recursive: true, mode: 0o700 });
    const context = session.fromPath(path, { cache: false });
    this.contexts.set(id, context);
    return context;
  }
  all(): Electron.Session[] { return [...this.contexts.values()]; }
  dispose(): void {
    // This exact path is generated by mkdtemp, never supplied by a user/extension.
    if (this.directory) { rmSync(this.directory, { recursive: true, force: true }); this.directory = undefined; }
    this.contexts.clear();
  }
}
